"""empty message

Revision ID: fa6f970ab20f
Revises: 262af6420438
Create Date: 2023-06-09 22:46:35.173007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6f970ab20f'
down_revision = '262af6420438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sexual_interests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sexual_interests', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
